#page title
page_title                                : Dagangan - Stok Warung dengan Mudah dan Murah                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.dagangan.store                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://i.ibb.co/N67bSvk/DGNICON.png                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Dagangan                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Stok Warung dengan Mudah dan Murah # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Dagangan merupakan platform online pembelian produk secara grosir yang diciptakan untuk memajukan UMKM. Kami memiliki sistem pemesanan yang matang, layanan pengiriman cepat, fitur yang lengkap untuk mempersiapkan Anda mengembangkan dan memperbesar bisnis di Indonesia. Tujuan kamu untuk membantu semua toko retail offline dengan menyediakan barang terbaik dengan harga yang sangat bersaing.                                      

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dagangan Team                              
your_link                                 : https://www.dagangan.com                     
your_city                                 : Jakarta                                
email_address                             : info@dagangan.com
facebook_username                         :                                           
instagram_username                        : dagangan
twitter_username                          : dagangan
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Pendapatan Tambahan
    description                           : Bisa berdagang dengan tetap menjalani aktivitas sehari-hari seperti biasanya
    fontawesome_icon_name                 : magic
    
  - title                                 : Akses ke Modal Tambahan
    description                           : Nikmati tambahan modal usaha tanpa jaminan dengan syarat yang simple banget dan bebas ribet
    fontawesome_icon_name                 : mobile

  - title                                 : Murah, Mudah, Lengkap
    description                           : Semua bisa kamu jual disini dengan harga yang bersaing hanya dalam 1 aplikasi
    fontawesome_icon_name                 : play-circle

#  - title                                 : Automatic Icon and Metadata
#    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
#   fontawesome_icon_name                 : sync

#  - title                                 : Easy to Tweak
#    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : adjust
  
#  - title                                 : Feature List
#    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#   fontawesome_icon_name                 : star

#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down

#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : link

#  - title                                 : FontAwesome Support
#    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : info-circle

#  - title                                 : # New Feature Title
#    description                           : # New Feature Description
#    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#FFFFFF"
topbar_transparency                       : 1
topbar_title_color                        : "#009Abf"

cover_image                               : https://i.ibb.co/w6Fnx0s/bg.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
